name: artificial_delay
description: A dart package to simulate artificial delays from volatile data providers.
version: 1.0.2
repository: https://www.github.com/tytydraco/artificial_delay

environment:
  sdk: '>=2.17.1 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
  very_good_analysis: ^3.0.1
